package main

import (
	"bytes"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/Clawdlinux/agentic-operator-core/pkg/agentctl"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	dynamicfake "k8s.io/client-go/dynamic/fake"
	"k8s.io/client-go/kubernetes/fake"
	k8stesting "k8s.io/client-go/testing"
)

func TestHandleDemoRendersEvidenceConsole(t *testing.T) {
	server, err := NewServer(nil, nil, TemplatesFS())
	if err != nil {
		t.Fatalf("NewServer() error = %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/demo", nil)
	res := httptest.NewRecorder()

	server.handleDemo(res, req)

	if res.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", res.Code, http.StatusOK)
	}

	body := res.Body.String()
	for _, want := range []string{
		`href="/theme/clawdlinux-theme.css"`,
		`src="/theme/clawdlinux-wordmark.svg"`,
		`alt="Clawdlinux"`,
		"Governance evidence console",
		">CONFIG ONLY</span>",
		">PRIOR RUN</span>",
		"No OPA evidence",
		"Runtime pod state unavailable",
		"No packet enforcement test",
		"gVisor admission dry-run",
		"NetworkPolicy object presence",
		"The audit receipt is a prior-run fixture. This console does not query current-run audit generation.",
		"no pod or packet test",
		`hx-trigger="every 5s"`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("demo body missing %q", want)
		}
	}

	sharedThemeIndex := strings.Index(body, `href="/theme/clawdlinux-theme.css"`)
	localStyleIndex := strings.Index(body, `href="/static/style.css"`)
	if sharedThemeIndex == -1 || localStyleIndex == -1 || sharedThemeIndex > localStyleIndex {
		t.Fatal("shared theme must load before local styles")
	}
	if count := strings.Count(body, "OPA"); count != 1 {
		t.Fatalf("demo body contains %d OPA references, want disclaimer only", count)
	}

	for _, stale := range []string{
		"OPA checks tool scope",
		"Policy gated",
		"gpt-4o-mini",
		"Secure Research Swarm",
		"$0.0142",
		"Audit trail",
		"Audit ready",
		"Current audit trail",
		"Current attestation",
		"Attestation verified",
		"Current workload generated no audit fixture",
		"not generated by the current workload",
		"3 agents",
		"No external data egress",
		"AgentWorkload running",
		"Live agent graph",
		"Agent graph",
		"Agentic Operator",
	} {
		if strings.Contains(body, stale) {
			t.Fatalf("demo body contains stale claim %q", stale)
		}
	}

	for label, want := range map[string]int{
		">LIVE</span>":        0,
		">CONFIG ONLY</span>": 1,
		">PRIOR RUN</span>":   1,
	} {
		if count := strings.Count(body, label); count != want {
			t.Errorf("demo body contains %d %s labels, want %d", count, label, want)
		}
	}
}

func TestHandleLoginRendersClawdlinuxEvidenceConsoleBranding(t *testing.T) {
	server, err := NewServer(nil, nil, TemplatesFS())
	if err != nil {
		t.Fatalf("NewServer() error = %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/auth/login", nil)
	res := httptest.NewRecorder()

	server.handleLogin(res, req)

	if res.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", res.Code, http.StatusOK)
	}

	body := res.Body.String()
	for _, want := range []string{
		`href="/theme/clawdlinux-theme.css"`,
		`href="/static/style.css"`,
		`src="/theme/clawdlinux-wordmark.svg"`,
		`alt="Clawdlinux"`,
		"Governance evidence console",
		`method="POST" action="/auth/login"`,
		`<footer class="footer login-footer">`,
		`<span>Clawdlinux</span>`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("login body missing %q", want)
		}
	}

	sharedThemeIndex := strings.Index(body, `href="/theme/clawdlinux-theme.css"`)
	localStyleIndex := strings.Index(body, `href="/static/style.css"`)
	if sharedThemeIndex == -1 || localStyleIndex == -1 || sharedThemeIndex > localStyleIndex {
		t.Error("shared theme must load before local styles on login")
	}

	for _, stale := range []string{"agentctl", "Agentic Operator Web UI", "⚙"} {
		if strings.Contains(body, stale) {
			t.Errorf("login body contains stale branding %q", stale)
		}
	}
}

func TestApprovalPartialsRenderTextControlsWithHTMXContracts(t *testing.T) {
	server, err := NewServer(nil, nil, TemplatesFS())
	if err != nil {
		t.Fatalf("NewServer() error = %v", err)
	}

	workload := agentctl.WorkloadRow{
		Name:      "review-required",
		Namespace: "regulated-team",
		Status:    "PendingApproval",
	}
	detail := agentctl.WorkloadDetail{
		Name:      workload.Name,
		Namespace: workload.Namespace,
		Phase:     workload.Status,
	}
	tests := []struct {
		name     string
		template string
		data     map[string]interface{}
		wants    []string
	}{
		{
			name:     "workload list",
			template: "workloads.html",
			data: map[string]interface{}{
				"Workloads": []agentctl.WorkloadRow{workload},
				"CSRFToken": "test-csrf",
			},
			wants: []string{
				`action="/workloads/regulated-team/review-required/approve"`,
				`hx-post="/workloads/regulated-team/review-required/approve"`,
				`action="/workloads/' + ns + '/' + name + '/reject"`,
				`hx-post="/workloads/' + ns + '/' + name + '/reject"`,
				`hx-target="#workload-table"`,
				`title="Approve">Approve</button>`,
				`title="Reject"`,
				`Submit rejection</button>`,
			},
		},
		{
			name:     "workload detail",
			template: "describe.html",
			data: map[string]interface{}{
				"Detail":    detail,
				"CSRFToken": "test-csrf",
			},
			wants: []string{
				`action="/workloads/regulated-team/review-required/approve"`,
				`hx-post="/workloads/regulated-team/review-required/approve"`,
				`action="/workloads/regulated-team/review-required/reject"`,
				`hx-post="/workloads/regulated-team/review-required/reject"`,
				`hx-target="#workload-table"`,
				`title="Approve">Approve</button>`,
				`title="Reject">Submit rejection</button>`,
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			var rendered bytes.Buffer
			if err := server.tmpl.ExecuteTemplate(&rendered, test.template, test.data); err != nil {
				t.Fatalf("ExecuteTemplate(%q) error = %v", test.template, err)
			}

			body := rendered.String()
			for _, want := range test.wants {
				if !strings.Contains(body, want) {
					t.Errorf("rendered partial missing %q", want)
				}
			}
			for _, glyph := range []string{"✓", "✗"} {
				if strings.Contains(body, glyph) {
					t.Errorf("rendered partial contains forbidden glyph %q", glyph)
				}
			}
		})
	}
}

func TestHandleDemoRendersLiveWorkloadEvidence(t *testing.T) {
	workload := newDemoWorkload()
	kube := fake.NewClientset(newDemoRuntimePod("  GVisor  "))
	client := &agentctl.Client{
		Dynamic: dynamicfake.NewSimpleDynamicClientWithCustomListKinds(
			runtime.NewScheme(),
			map[schema.GroupVersionResource]string{
				agentctl.AgentWorkloadGVR: "AgentWorkloadList",
			},
			workload,
		),
		Kube:      kube,
		Discovery: kube.Discovery(),
	}

	server, err := NewServer(client, nil, TemplatesFS())
	if err != nil {
		t.Fatalf("NewServer() error = %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/demo", nil)
	res := httptest.NewRecorder()

	server.handleDemo(res, req)

	body := res.Body.String()
	for _, want := range []string{
		"Cluster interaction available",
		"Runtime pods",
		"evidence-workload-runner",
		"evidence-workload",
		"regulated-team",
		"GVisor",
		"ghcr.io/clawdlinux/research-agent:v0.2.0",
		"anthropic/claude-sonnet-4",
		"$0.4321",
		"gVisor pod observed in cluster runtime state",
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("demo body missing %q", want)
		}
	}

	liveEvidenceIndex := strings.Index(body, "Cluster interaction available")
	consoleIndex := strings.Index(body, "Governance evidence console")
	if liveEvidenceIndex == -1 || consoleIndex == -1 {
		t.Fatalf("expected live evidence and console content")
	}
	if liveEvidenceIndex > consoleIndex {
		t.Fatalf("live evidence should appear before console overview in cluster-connected demo")
	}

	for _, source := range []string{"runtime-pods", "workloads", "workload-aggregate", "cluster-status"} {
		assertEvidenceSourceState(t, body, source, "LIVE")
	}
}

func TestHandleDemoDerivesAggregateFromSingleWorkloadSnapshot(t *testing.T) {
	dynamicClient := newDemoDynamicClient(newDemoWorkload())
	workloadListCalls := 0
	dynamicClient.PrependReactor("list", "agentworkloads", func(k8stesting.Action) (bool, runtime.Object, error) {
		workloadListCalls++
		if workloadListCalls > 1 {
			return true, nil, errors.New("transient second list failure")
		}
		return false, nil, nil
	})
	kube := fake.NewClientset()
	client := &agentctl.Client{
		Dynamic:   dynamicClient,
		Kube:      kube,
		Discovery: kube.Discovery(),
	}

	body := renderDemo(t, client)

	if workloadListCalls != 1 {
		t.Fatalf("AgentWorkload list calls = %d, want 1", workloadListCalls)
	}
	assertEvidenceSourceState(t, body, "workload-aggregate", "LIVE")
	assertEvidenceSourceContains(t, body, "workload-aggregate", "$0.4321")
	assertEvidenceSourceContains(t, body, "workload-aggregate", "Workload count: 1")
	assertEvidenceSourceState(t, body, "cluster-status", "LIVE")
}

func TestHandleDemoKeepsAggregateUnavailableWhenWorkloadSnapshotFails(t *testing.T) {
	dynamicClient := newDemoDynamicClient()
	dynamicClient.PrependReactor("list", "agentworkloads", func(k8stesting.Action) (bool, runtime.Object, error) {
		return true, nil, errors.New("workload source unavailable")
	})
	kube := fake.NewClientset()
	client := &agentctl.Client{
		Dynamic:   dynamicClient,
		Kube:      kube,
		Discovery: kube.Discovery(),
	}

	body := renderDemo(t, client)

	assertEvidenceSourceState(t, body, "workloads", "UNAVAILABLE")
	assertEvidenceSourceState(t, body, "workload-aggregate", "UNAVAILABLE")
	assertEvidenceSourceContains(t, body, "workload-aggregate", "Aggregate workload count and cost unavailable")
	assertEvidenceSourceState(t, body, "cluster-status", "LIVE")
}

func TestHandleDemoReportsNoObservedGVisorPod(t *testing.T) {
	client := &agentctl.Client{Kube: fake.NewClientset(newDemoRuntimePod("runc"))}
	body := renderDemo(t, client)

	if !strings.Contains(body, "No scheduled gVisor pod observed in cluster runtime state") {
		t.Fatal("demo body must scope absent gVisor evidence to observed cluster runtime state")
	}
	if strings.Contains(body, "<li>gVisor pod observed in cluster runtime state</li>") {
		t.Fatal("demo body must not claim a gVisor pod was observed")
	}
}

func TestHandleDemoTracksPartialSourceProvenance(t *testing.T) {
	tests := []struct {
		name   string
		client *agentctl.Client
		assert func(*testing.T, string)
	}{
		{
			name: "pods succeed workloads fail",
			client: func() *agentctl.Client {
				dynamicClient := newDemoDynamicClient()
				dynamicClient.PrependReactor("list", "agentworkloads", func(k8stesting.Action) (bool, runtime.Object, error) {
					return true, nil, errors.New("workload source unavailable")
				})
				return &agentctl.Client{
					Kube:    fake.NewClientset(newDemoRuntimePod("gvisor")),
					Dynamic: dynamicClient,
				}
			}(),
			assert: func(t *testing.T, body string) {
				assertEvidenceSourceState(t, body, "runtime-pods", "LIVE")
				assertEvidenceSourceContains(t, body, "runtime-pods", "evidence-workload-runner")
				assertEvidenceSourceState(t, body, "workloads", "UNAVAILABLE")
				assertEvidenceSourceContains(t, body, "workloads", "AgentWorkload source unavailable")
				assertEvidenceSourceState(t, body, "workload-aggregate", "UNAVAILABLE")
				assertEvidenceSourceState(t, body, "cluster-status", "UNAVAILABLE")
			},
		},
		{
			name: "workloads succeed pods fail",
			client: func() *agentctl.Client {
				kube := fake.NewClientset()
				kube.PrependReactor("list", "pods", func(k8stesting.Action) (bool, runtime.Object, error) {
					return true, nil, errors.New("pod source unavailable")
				})
				return &agentctl.Client{
					Kube:    kube,
					Dynamic: newDemoDynamicClient(newDemoWorkload()),
				}
			}(),
			assert: func(t *testing.T, body string) {
				assertEvidenceSourceState(t, body, "runtime-pods", "UNAVAILABLE")
				assertEvidenceSourceContains(t, body, "runtime-pods", "Runtime pod source unavailable")
				assertEvidenceSourceState(t, body, "workloads", "LIVE")
				assertEvidenceSourceContains(t, body, "workloads", "anthropic/claude-sonnet-4")
				assertEvidenceSourceContains(t, body, "workloads", "$0.4321")
				assertEvidenceSourceState(t, body, "workload-aggregate", "LIVE")
				assertEvidenceSourceContains(t, body, "workload-aggregate", "$0.4321")
				assertEvidenceSourceState(t, body, "cluster-status", "UNAVAILABLE")
			},
		},
		{
			name: "discovery fails while workloads succeed",
			client: func() *agentctl.Client {
				kube := fake.NewClientset()
				kube.Fake.PrependReactor("get", "version", func(k8stesting.Action) (bool, runtime.Object, error) {
					return true, nil, errors.New("status source unavailable")
				})
				return &agentctl.Client{
					Kube:      kube,
					Dynamic:   newDemoDynamicClient(newDemoWorkload()),
					Discovery: kube.Discovery(),
				}
			}(),
			assert: func(t *testing.T, body string) {
				assertEvidenceSourceState(t, body, "workloads", "LIVE")
				assertEvidenceSourceContains(t, body, "workloads", "anthropic/claude-sonnet-4")
				assertEvidenceSourceContains(t, body, "workloads", "$0.4321")
				assertEvidenceSourceState(t, body, "workload-aggregate", "LIVE")
				assertEvidenceSourceContains(t, body, "workload-aggregate", "$0.4321")
				assertEvidenceSourceState(t, body, "cluster-status", "UNAVAILABLE")
				assertEvidenceSourceContains(t, body, "cluster-status", "Cluster status unavailable")
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			body := renderDemo(t, test.client)
			if !strings.Contains(body, "Cluster interaction available") {
				t.Fatal("partial source success must report cluster interaction")
			}
			test.assert(t, body)
		})
	}
}

func renderDemo(t *testing.T, client *agentctl.Client) string {
	t.Helper()
	server, err := NewServer(client, nil, TemplatesFS())
	if err != nil {
		t.Fatalf("NewServer() error = %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/demo", nil)
	res := httptest.NewRecorder()
	server.handleDemo(res, req)
	if res.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", res.Code, http.StatusOK)
	}
	return res.Body.String()
}

func assertEvidenceSourceState(t *testing.T, body, source, state string) {
	t.Helper()
	section := evidenceSourceHTML(t, body, source)
	if !strings.Contains(section, ">"+state+"</span>") {
		t.Fatalf("source %q does not report %q: %s", source, state, section)
	}
	if state != "LIVE" && strings.Contains(section, ">LIVE</span>") {
		t.Fatalf("source %q inherits unsupported LIVE state: %s", source, section)
	}
}

func assertEvidenceSourceContains(t *testing.T, body, source, want string) {
	t.Helper()
	section := evidenceSourceHTML(t, body, source)
	if !strings.Contains(section, want) {
		t.Fatalf("source %q missing %q: %s", source, want, section)
	}
}

func evidenceSourceHTML(t *testing.T, body, source string) string {
	t.Helper()
	marker := `data-evidence-source="` + source + `"`
	markerIndex := strings.Index(body, marker)
	if markerIndex == -1 {
		t.Fatalf("demo body missing source boundary %q", source)
	}
	start := strings.LastIndex(body[:markerIndex], "<article")
	if start == -1 {
		t.Fatalf("source %q has no article boundary", source)
	}
	endOffset := strings.Index(body[markerIndex:], "</article>")
	if endOffset == -1 {
		t.Fatalf("source %q has no closing article boundary", source)
	}
	return body[start : markerIndex+endOffset+len("</article>")]
}

func newDemoDynamicClient(objects ...runtime.Object) *dynamicfake.FakeDynamicClient {
	return dynamicfake.NewSimpleDynamicClientWithCustomListKinds(
		runtime.NewScheme(),
		map[schema.GroupVersionResource]string{
			agentctl.AgentWorkloadGVR: "AgentWorkloadList",
		},
		objects...,
	)
}

func newDemoWorkload() *unstructured.Unstructured {
	createdAt := metav1.NewTime(time.Now().Add(-time.Minute))
	return &unstructured.Unstructured{Object: map[string]interface{}{
		"apiVersion": "agentic.clawdlinux.org/v1alpha1",
		"kind":       "AgentWorkload",
		"metadata": map[string]interface{}{
			"name":              "evidence-workload",
			"namespace":         "regulated-team",
			"creationTimestamp": createdAt.Format(time.RFC3339),
			"annotations": map[string]interface{}{
				agentctl.CostAnnotationKey: "0.4321",
			},
		},
		"spec": map[string]interface{}{
			"model": "anthropic/claude-sonnet-4",
		},
		"status": map[string]interface{}{
			"phase": "Running",
		},
	}}
}

func newDemoRuntimePod(runtimeClass string) *corev1.Pod {
	return &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "evidence-workload-runner",
			Namespace: "argo-workflows",
			Labels: map[string]string{
				"agentic.io/job-id":         "evidence-workload",
				agentctl.RoleLabelKey:       "researcher",
				"app.kubernetes.io/part-of": "clawdlinux",
			},
		},
		Spec: corev1.PodSpec{
			RuntimeClassName: stringPtr(runtimeClass),
			Containers: []corev1.Container{{
				Name:  "agent",
				Image: "ghcr.io/clawdlinux/research-agent:v0.2.0",
			}},
		},
		Status: corev1.PodStatus{Phase: corev1.PodRunning},
	}
}

func stringPtr(value string) *string {
	return &value
}
