package main

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/Clawdlinux/agentic-operator-core/pkg/agentctl"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	dynamicfake "k8s.io/client-go/dynamic/fake"
	"k8s.io/client-go/kubernetes/fake"
)

func TestHandleDemoRendersEvidenceConsole(t *testing.T) {
	server, err := NewServer(nil, nil, TemplatesFS())
	if err != nil {
		t.Fatalf("NewServer() error = %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/demo", nil)
	res := httptest.NewRecorder()

	server.handleDemo(res, req)

	if res.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", res.Code, http.StatusOK)
	}

	body := res.Body.String()
	for _, want := range []string{
		`href="/theme/clawdlinux-theme.css"`,
		`src="/theme/clawdlinux-wordmark.svg"`,
		`alt="Clawdlinux"`,
		"Governance evidence console",
		">LIVE</span>",
		">CONFIG ONLY</span>",
		">PRIOR RUN</span>",
		"No OPA evidence",
		"No scheduled gVisor pod",
		"No packet enforcement test",
		"Current workload generated no audit fixture",
		"no pod or packet test",
		"not generated by the current workload",
		`hx-trigger="every 5s"`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("demo body missing %q", want)
		}
	}

	sharedThemeIndex := strings.Index(body, `href="/theme/clawdlinux-theme.css"`)
	localStyleIndex := strings.Index(body, `href="/static/style.css"`)
	if sharedThemeIndex == -1 || localStyleIndex == -1 || sharedThemeIndex > localStyleIndex {
		t.Fatal("shared theme must load before local styles")
	}
	if count := strings.Count(body, "OPA"); count != 1 {
		t.Fatalf("demo body contains %d OPA references, want disclaimer only", count)
	}

	for _, stale := range []string{
		"OPA checks tool scope",
		"gpt-4o-mini",
		"Secure Research Swarm",
		"Audit trail",
		"Policy gated",
		"Audit ready",
		"Agentic Operator",
	} {
		if strings.Contains(body, stale) {
			t.Fatalf("demo body contains stale claim %q", stale)
		}
	}
}

func TestHandleDemoRendersLiveWorkloadEvidence(t *testing.T) {
	createdAt := metav1.NewTime(time.Now().Add(-time.Minute))
	workload := &unstructured.Unstructured{Object: map[string]interface{}{
		"apiVersion": "agentic.clawdlinux.org/v1alpha1",
		"kind":       "AgentWorkload",
		"metadata": map[string]interface{}{
			"name":              "evidence-workload",
			"namespace":         "regulated-team",
			"creationTimestamp": createdAt.Format(time.RFC3339),
			"annotations": map[string]interface{}{
				agentctl.CostAnnotationKey: "0.4321",
			},
		},
		"spec": map[string]interface{}{
			"model": "anthropic/claude-sonnet-4",
		},
		"status": map[string]interface{}{
			"phase": "Running",
		},
	}}
	client := &agentctl.Client{
		Dynamic: dynamicfake.NewSimpleDynamicClientWithCustomListKinds(
			runtime.NewScheme(),
			map[schema.GroupVersionResource]string{
				agentctl.AgentWorkloadGVR: "AgentWorkloadList",
			},
			workload,
		),
		Kube: fake.NewClientset(&corev1.Pod{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "evidence-workload-runner",
				Namespace: "argo-workflows",
				Labels: map[string]string{
					"agentic.io/job-id":         "evidence-workload",
					agentctl.RoleLabelKey:       "researcher",
					"app.kubernetes.io/part-of": "clawdlinux",
				},
			},
			Spec: corev1.PodSpec{
				RuntimeClassName: stringPtr("gvisor"),
				Containers: []corev1.Container{{
					Name:  "agent",
					Image: "ghcr.io/clawdlinux/research-agent:v0.2.0",
				}},
			},
			Status: corev1.PodStatus{Phase: corev1.PodRunning},
		}),
	}

	server, err := NewServer(client, nil, TemplatesFS())
	if err != nil {
		t.Fatalf("NewServer() error = %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/demo", nil)
	res := httptest.NewRecorder()

	server.handleDemo(res, req)

	body := res.Body.String()
	for _, want := range []string{
		"LIVE",
		"Workload state and estimated cost read from the cluster",
		"Runtime pods",
		"evidence-workload-runner",
		"evidence-workload",
		"regulated-team",
		"gvisor",
		"ghcr.io/clawdlinux/research-agent:v0.2.0",
		"anthropic/claude-sonnet-4",
		"$0.4321",
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("demo body missing %q", want)
		}
	}

	liveEvidenceIndex := strings.Index(body, "Workload state and estimated cost read from the cluster")
	consoleIndex := strings.Index(body, "Governance evidence console")
	if liveEvidenceIndex == -1 || consoleIndex == -1 {
		t.Fatalf("expected live evidence and console content")
	}
	if liveEvidenceIndex > consoleIndex {
		t.Fatalf("live evidence should appear before console overview in cluster-connected demo")
	}
}

func stringPtr(value string) *string {
	return &value
}
